-- phpMyAdmin SQL Dump
-- version 2.8.2
-- http://www.phpmyadmin.net
-- 
-- Host: localhost
-- Generation Time: Dec 26, 2006 at 11:36 PM
-- Server version: 4.0.26
-- PHP Version: 4.4.4
-- 
-- Database: `blg_blog`
-- 

-- --------------------------------------------------------

-- 
-- Table structure for table `blg_article_art`
-- 

CREATE TABLE `blg_article_art` (
  `id_art` int(11) NOT NULL auto_increment,
  `idtop_art` int(11) NOT NULL default '0',
  `title_art` varchar(100) NOT NULL default '',
  `description_art` varchar(255) NOT NULL default '',
  `text_art` longtext NOT NULL,
  `date_art` datetime default NULL,
  PRIMARY KEY  (`id_art`)
) TYPE=MyISAM AUTO_INCREMENT=5 ;

-- 
-- Dumping data for table `blg_article_art`
-- 

INSERT INTO `blg_article_art` (`id_art`, `idtop_art`, `title_art`, `description_art`, `text_art`, `date_art`) VALUES (1, 1, 'Hand-coding PHP in Dreamweaver MX', 'An overview of some coding facilities in DW', 'Although Dreamweaver MX contains a range of built-in PHP server behaviors to perform various operations, if you''re building a complex site, you''ll soon find that you want to do something for which there isn''t a built-in server behavior. \r\nSince PHP is an open source product, it is widely supported by a range of open source developers and a huge user community. As a result PHP evolves much faster than other commercial languages, and the code is continuously updated with bug fixes, enhancements, and language extensions, which extend its capabilities.\r\n\r\nHand coding allows you to implement the latest PHP developments in your code as soon as they are released. It offers you total freedom to ensure that your web site does exactly what you want it to, and you are not just limited to the built in code generated by your development program.\r\n\r\nCode that you''ve written yourself can also interact with the Dreamweaver MX generated code, so you can create standard code quickly using the Dreamweaver MX server behaviors, and then modify it yourself to perform extra functions.\r\n\r\nWe''re now going to look at the many ways you can create and edit code (both PHP and HTML) in Dreamweaver MX.\r\n\r\n', '2004-07-20 19:04:00'),
(2, 1, 'Connecting to SQL database', 'Create a MySQL connection in Dreamweaver for dynamic applications', 'Once the MySQL user account has been set up and the site has been defined, you can connect to your MySQL database in Dreamweaver. Using the above settings, here are example settings for the MySQL Connection dialog box in Dreamweaver:\r\n\r\nConnection Name: choose a name (e.g. connEmp)\r\nMySQL Server: mysql1.myDomain.com\r\nUser Name: dbuser\r\nPassword: myPassword\r\nDatabase: enter the name of your database or click on the Select button to choose from a list of MySQL databases running on the server.\r\n\r\nNote: For the MySQL Server field you must enter localhost if PHP and MySQL are running on the same machine.', '2004-07-21 13:03:44'),
(3, 3, 'Allagash River Canoe Trip Journal', 'Adventures in the wilderness', 'I spent the last week of August paddling Maine''s Allagash Wilderness Waterway with Master Maine Guide Ray Reitze, Jr. Ray has been guiding trips on the Allagash and other Maine waterways for over 15 years. His guide service and school of wilderness living, Earthways, is located in Canaan, Maine. \r\n\r\nRay grew up in Maine under the tutelage of a native elder who taught Ray the lifeways of his people and the skills of living in the north woods. Ray passes on these skills through his guided trips, wilderness living skills courses, and philosophy courses. \r\n\r\nOur party of eight traveled in four of Ray''s handmade wood and canvas canoes. Three of the canoes, two 18 footers and a 20 footer, are made from the famous E. M. White pattern, while the fourth, a 17 footer, was more of a whitewater design. I had the good fortune to paddle the 20 footer for the week, and it was a treat. The E. M. White canoe was designed to be a freight canoe, but handles like a dream in all types of water. It can be rolled up to the gunnel without being swamped, and was a joy to paddle and pole.\r\n', '2004-07-21 13:05:02'),
(4, 2, 'Stamp collecting', 'Some guidelines and advice for stamp collecting', 'You too can join the throngs of stamp enthusiasts around the world by folllowing the simple steps explained in this article. And when you begin your collection, you will become a philatelist and start the old-age hobby of collecting stamps. \r\nFirst, in order to start your fascinating collection, you will need to purchase a few supplies from your local hobby store. You will need a pair of tweezers to use when you handle your stamps so they do not become soiled; a stamp album to keep your collection clean and free from dirt and stains; hinges to hold certain types of stamps in your album; plastic holders to hold other types of stamps in your album, specifically the new, uncirculated ones; and, of course, some stamps. Note: Certai stamp albums are designed to hold the stamps without the use of hinges or holders. Purchasing this type of album will save you time and money in the long run, and is really the best way to go. \r\nThe stamps that you collect may either be new or used. You can either purchase some stamps to start your collection out, or ask friends and family members to save their stamps off of envelopes, cards, etc. they receive, for you. You can add to your collection by saving the stamps off of your own mail, too. If someone you know is going to take a trip overseas to a faraway land, then you can get some foreign stamps easily that way too. ', '2006-05-03 14:50:14');

-- --------------------------------------------------------

-- 
-- Table structure for table `blg_comment_com`
-- 

CREATE TABLE `blg_comment_com` (
  `id_com` int(11) NOT NULL auto_increment,
  `idart_com` int(11) NOT NULL default '0',
  `text_com` text NOT NULL,
  `idusr_com` int(11) NOT NULL default '0',
  `date_com` datetime default NULL,
  `valid_com` tinyint(4) NOT NULL default '0',
  PRIMARY KEY  (`id_com`)
) TYPE=MyISAM AUTO_INCREMENT=8 ;

-- 
-- Dumping data for table `blg_comment_com`
-- 

INSERT INTO `blg_comment_com` (`id_com`, `idart_com`, `text_com`, `idusr_com`, `date_com`, `valid_com`) VALUES (3, 1, 'Do you guys know any free Dreamweaver extensions that can help me generate a breadcrumbs navigation trail? Thanks!', 2, '2004-10-20 12:51:42', 1),
(5, 3, 'Where can I buy a hand-made canoe? I used to have one from my father, but it''s not safe to ride anymore. I also found a lot of local shops selling boats, but I didn''t like any of their products.\r\n\r\nCould you please help me if you happen to know someone who is still manufacturing traditional canoes?', 2, '2004-10-20 12:54:32', 1),
(4, 2, 'I use PostgreSQL. How is the connecting operation different from MySQL?\r\n\r\nDo I need any special rights to manage my databases on a PostgreSQL server?', 3, '2004-10-20 12:52:23', 1),
(1, 1, 'What is a server behavior? Is it a code snippet? Do I have to create server behaviors manually, or can I generate them using the Dreamweaver GUI?', 4, '2004-10-20 12:50:08', 1),
(2, 1, 'I don''t like to hand-code in Dreamweaver, because all the panels take up space and I can''t see all the code. The debugger is quite powerful, though.\r\nI usually use a professional PHP editor for large-scale projects.', 3, '2004-10-20 12:51:05', 1),
(6, 4, 'What is the most expensive stamp in the world? What is the country that issued it?', 3, '2004-10-20 12:57:36', 1),
(7, 1, 'Betty test', 4, '2006-05-03 15:16:05', 1);

-- --------------------------------------------------------

-- 
-- Table structure for table `blg_topic_top`
-- 

CREATE TABLE `blg_topic_top` (
  `id_top` int(11) NOT NULL auto_increment,
  `title_top` varchar(100) NOT NULL default '',
  `description_top` varchar(255) NOT NULL default '',
  PRIMARY KEY  (`id_top`)
) TYPE=MyISAM AUTO_INCREMENT=4 ;

-- 
-- Dumping data for table `blg_topic_top`
-- 

INSERT INTO `blg_topic_top` (`id_top`, `title_top`, `description_top`) VALUES (1, 'Programming Techniques', 'Special tricks and tips for programming in PHP and ASP'),
(2, 'Hobbies', 'My favorite music and movies and my personal interests'),
(3, 'Vacations', 'Trip journals, holidays');

-- --------------------------------------------------------

-- 
-- Table structure for table `blg_user_usr`
-- 

CREATE TABLE `blg_user_usr` (
  `id_usr` int(11) NOT NULL auto_increment,
  `username_usr` varchar(32) NOT NULL default '',
  `password_usr` varchar(32) NOT NULL default '',
  `email_usr` varchar(100) NOT NULL default '',
  `firstname_usr` varchar(255) NOT NULL default '',
  `lastname_usr` varchar(255) NOT NULL default '',
  `address_usr` varchar(255) default NULL,
  `regtime_usr` datetime default NULL,
  `level_usr` varchar(10) NOT NULL default 'user',
  PRIMARY KEY  (`id_usr`)
) TYPE=MyISAM AUTO_INCREMENT=5 ;

-- 
-- Dumping data for table `blg_user_usr`
-- 

INSERT INTO `blg_user_usr` (`id_usr`, `username_usr`, `password_usr`, `email_usr`, `firstname_usr`, `lastname_usr`, `address_usr`, `regtime_usr`, `level_usr`) VALUES (1, 'admin', 'admin', 'carlos@karljohansen.com', 'John', 'Doe', 'New York', '2004-07-26 17:44:31', 'admin'),
(2, 'Angel', 'skyscrapers', 'angel@domain.org', 'Laura', 'Palmer', '5-th Avenue, Washington DC, USA', '2004-10-20 12:43:00', 'user'),
(4, 'Betty', 'test', 'beth@location.com', 'Elisabeth', 'Taylor', 'Bd Vasile Milea, nr. 89, Bucharest, Romania', '2004-11-04 16:05:04', 'user');
